### ISSUE TITLE
В реализации методов DAO по разному записывается имя таблицы

### ISSUE THREAD

**Issue by LDelOff** [SovietHub/SQL-table_pre-project_1.1.4#1]
Например, в createUsersTable() у тебя 'Persons'
В cleanUsersTable() без кавычек
В чем соль?

**Comment by SovietHub** [comment]
На самом деле у меня не **'**Persons**'**, а ![image](https://user-images.githubusercontent.com/85436689/188277643-120570b8-243d-4226-b052-9f23c1d03c93.png)
В первом случае это обычный литерал, куда можно что угодно запихивать,а во втором случае название таблицы

А касательно твоего вопроса, то так принято ограничивать имена сущностей в БД
Бывает ситуация, когда мы можем назвать таблицу или поле, как какую-нибудь команду в SQL
И чтобы SQL понял, что я передаю ему именно название, а не как какую-либо операцию заключаем названия таблиц и полей в ![image](https://user-images.githubusercontent.com/85436689/188277670-d266c187-1fca-4f3e-b792-8a5f4de5afde.png)

NULL - ничего не отобразит
 'NULL' - напишет NULL, 
![image](https://user-images.githubusercontent.com/85436689/188277660-3998fc53-7beb-4108-91b0-0bd253da2125.png)
 - будет искать в БД NULL как имя

Это правило хорошего тона, которое когда-то поможет избежать ошибки, в методе createUsersTable() у меня объёмный SQL запрос, с конкатенацией, и чтобы не запутаться что-где и не допустить ошибки написан образцовый запрос

А в методе cleanUsersTable() SQL запрос из 3 слов и я забил, ибо SQL итак поймёт что я ему передал.Ещё и команды с маленькой буквы написал. 
В createUsersTable() это была бы плохочитабельная мешанина.

**Comment by SovietHub** [comment]
Местный чатик не отображает обратные кавычки))
Везде где выделено серым используются внутренние кавычки

![image](https://user-images.githubusercontent.com/85436689/188277623-293f2313-a85e-4599-8224-2db61f637e28.png)

**Comment by SovietHub** [comment]
Гитхаб не пропускает обратные кавычки, поэтому я вставлял картинки, и выглядит не оч

**Comment by SovietHub** [comment]
Про правила грамотного написания SQL запросов мне никто тогда не сказал, так что держи
https://www.sqlstyle.guide/ru/#хороший-стиль
